name: 'Code quality exporter'
branding:
  icon: 'award'  
  color: 'green'
description: 'Collect data from eslint and export to database/spreadsheet'
inputs:
  result_file:
    description: 'Path of the json file with result of eslint run'
    required: false
  project_name:
    description: 'The project name that will be sent to database/spreadsheet'
    required: true
  spreadsheet_id:
    description: 'The id of target spreadsheet'
    required: true
  google_service_account_email:
    description: 'Service account email to access the spreadsheet'
    required: true
  google_private_key:
    description: 'The service account private key'
    required: true
  eslint_project_list:
    description: 'A list of all paths to be analyzed'
    required: false
    default: '.'
  eslint_extensions:
    description: 'A list of file extensions to be scanned separated by comma. Ex: .js,.ts'
    required: false
    default: '.js,.ts,.jsx'
  exit_with_error_when_errors:
    description: 'Exit process with code 1 when there has some error'
    required: false
    default: 'true'
  exit_with_error_when_warning:
    description: 'Exit process with code 1 when there has some warning'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'
