name: validate

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint

  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci


      - name: Parse taskdefinition file for production environment
        uses: edgardleal/mustache-template-action@v1.0.4
          # if: contains(github.ref, 'master')
        env:
          ENV: prd
        with:
          input: package.json
          output: parsed.json
          debug: true

      - name: Run eslint and send data to collector
        uses: ./
        with:
            spreadsheet_id: ${{ secrets.ESLINT_COLLECTOR_SPREADSHEET_ID }}
            google_service_account_email: ${{ secrets.ESLINT_COLLECTOR_GOOGLE_SERVICE_ACCOUNT_EMAIL }}
            google_private_key: ${{ secrets.ESLINT_COLLECTOR_GOOGLE_PRIVATE_KEY }}
            eslint_project_list: ./
            project_name: datacollectorv3
